"""
RADS modules generator.

Single source for:
  addons/modules/CfgVehicles.hpp     (Zeus + 3DEN module classes, every label a stringtable key)
  addons/modules/stringtable.xml     (module names/attributes/descriptions + Zeus dialog strings in ZEUS)

The 3DEN "Detection Settings" module offers the settings listed in EDEN_SETTINGS, with titles and
tooltips taken from the main stringtable (generated by tools/gen_settings.py, imported here).

Run from the repository root:  python tools/gen_modules.py
"""
import os
import html
import importlib.util

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NL = "\\n"

spec = importlib.util.spec_from_file_location("gen_settings", os.path.join(ROOT, "tools", "gen_settings.py"))
gs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gs)
SETTINGS = {e["name"]: e for _, _, s in gs.CATS for e in s}

STR = {}  # key -> English


def s(key, text):
    STR[key] = text
    return f"CSTRING({key})"


# ----------------------------------------------------------------------- Zeus modules
ZEUS = [
    ("ROOT_ADS_Zeus_Settings", "zeusSettings", "Detection Settings"),
    ("ROOT_ADS_Zeus_SyncSettings", "zeusSyncSettings", "Suspicion Sync Settings"),
    ("ROOT_ADS_Zeus_PursuitSettings", "zeusPursuitSettings", "Pursuit & Checkpoint Settings"),
    ("ROOT_ADS_Zeus_TruceSettings", "zeusTruceSettings", "Safe Zone Truce Settings"),
    ("ROOT_ADS_Zeus_AddZone", "zeusAddZone", "Add Detection Zone"),
    ("ROOT_ADS_Zeus_RemoveZones", "zeusRemoveZones", "Remove Detection Zones"),
    ("ROOT_ADS_Zeus_UnitCover", "zeusUnitCover", "Unit Cover Profile"),
    ("ROOT_ADS_Zeus_Vehicle", "zeusVehicle", "Vehicle Disguise"),
    ("ROOT_ADS_Zeus_GroupProfile", "zeusGroupProfile", "AI Group Profile"),
    ("ROOT_ADS_Zeus_GearReference", "zeusGearReference", "Enemy Gear Reference"),
    ("ROOT_ADS_Zeus_OrderPursuit", "zeusOrderPursuit", "Order Pursuit / Call Off"),
    ("ROOT_ADS_Zeus_Compromise", "zeusCompromise", "Compromise / Restore Cover"),
    ("ROOT_ADS_Zeus_Toggle", "zeusToggle", "Enable / Disable RADS"),
    ("ROOT_ADS_Zeus_Bulletin", "zeusBulletin", "Radio Bulletin"),
    ("ROOT_ADS_Zeus_Inspect", "zeusInspect", "Inspect Detection Status"),
]

# ----------------------------------------------------------------------- 3DEN settings module content
EDEN_SETTINGS = [
    "enabled", "buildRate", "decayRate", "suspiciousThreshold", "identifyThreshold", "maxRange", "identifyRange",
    "instantRange", "forgetAfter", "memoryTime", "heatDuration", "firedRadius",
    "allowHostileVeh", "sameFactionVehMult", "hostileVehMult",
    "armoredDetect", "armoredHullMult", "armoredDrivingOnly", "vehOpticsEnabled", "vehOpticsMult",
    "gearCompareMode", "gearRefSource",
    "metaDetect", "metaMaxSpeed", "hiddenCrewAny", "reverseMult", "rearFacingMult",
    "ramCompromise", "ramBurn",
    "convoyMode", "convoySpillSusp",
    "shareMode", "shareRadius",
    "bulletinEnabled", "bulletinChance", "bulletinRange", "burnDuration", "wantedDuration",
    "informantsEnabled", "theftEnabled",
    "aiAware", "aiWatch", "aiGlance", "aiLook", "debugClients",
]
EDEN_PURSUIT = [
    "syncEnabled", "syncRadius", "syncDelay", "syncFactor", "syncMin", "syncCanIdentify", "syncRespectSig", "appearanceChangeKeep",
    "pursuitEnabled", "followEnabled", "followThreshold", "pursuitMaxGroups", "pursuitMaxTime",
    "leashEnabled", "leashFoot", "leashVehicle", "leashGiveUp",
    "stopFreeze", "stopSignalRange", "stopSignalInterval", "stopFleeDistance",
    "followDistance", "stopTimeout", "stopSignalHorn", "stopSignalLights", "alertRadius", "alertSuspicion",
    "inspectTime", "inspectMult", "inspectClearSusp", "fleeDistance", "fleeBulletin", "fleeBurn",
    "lambsDisableDuringPursuit", "lambsHuntOnCompromise",
    "truceEnabled", "truceMaxStay", "truceWarn", "truceCareless", "truceBreakScope", "truceBreakOnAim", "truceCooldown",
]


def keep_value(e):
    return -9999 if e["kind"] == "SLIDER" and e["lo"] < 0 else -1


def setting_attr(name):
    e = SETTINGS[name]
    title = f'"$STR_root_ads_main_{name}"'
    tip = f'"$STR_root_ads_main_{name}_desc"'
    cls = f"ROOT_ADS_S_{name}"
    if e["kind"] == "CHECKBOX":
        return f"ATTR_TRI_RAW({cls},{title},{tip});"
    if e["kind"] == "SLIDER":
        return f"ATTR_NUM_RAW({cls},{title},{tip},{keep_value(e)});"
    if e["kind"] == "LIST":
        lines = [f"class {cls}: Combo {{",
                 f'    property = "{cls}";',
                 f"    displayName = {title};",
                 f"    tooltip = {tip};",
                 '    typeName = "NUMBER";',
                 "    defaultValue = -1;",
                 "    class Values {",
                 '        class Keep { name = CSTRING(keepSetting); value = -1; };']
        for i, v in enumerate(e["values"]):
            lines.append(f'        class V{i} {{ name = "$STR_root_ads_main_{name}_opt{i}"; value = {v}; }};')
        lines += ["    };", "};"]
        return "\n".join(lines)
    raise ValueError(name)


def indent(text, n):
    pad = " " * n
    return "\n".join(pad + l if l else l for l in text.split("\n"))


# ----------------------------------------------------------------------- shared strings
s("category", "Root's Adaptive Detection")
s("keepSetting", "Keep setting")
s("off", "Off")
s("on", "On")
s("auto", "Auto")

for cls, _fnc, name in ZEUS:
    s(f"zeus_{cls}", name)


def eden(cls, fnc, name, trigger, attrs, desc, extra=""):
    return dict(cls=cls, fnc=fnc, name=s(f"eden_{cls}", name), trigger=trigger, attrs=attrs, desc=s(f"eden_{cls}_desc", desc), extra=extra)


def a_num(cls, label, tip, default):
    return f"ATTR_NUM({cls},{s(cls, label)},{s(cls + '_desc', tip)},{default});"


def a_str(cls, label, tip, default):
    return f'ATTR_STR({cls},{s(cls, label)},{s(cls + "_desc", tip)},"""{default}""");'


def a_bool(cls, label, tip, default):
    return f"ATTR_BOOL({cls},{s(cls, label)},{s(cls + '_desc', tip)},{'true' if default else 'false'});"


def a_tri(cls, label, tip):
    return f"ATTR_TRI({cls},{s(cls, label)},{s(cls + '_desc', tip)});"


def a_combo(cls, label, tip, type_name, default, options):
    lines = [f"class {cls}: Combo {{", f'    property = "{cls}";', f"    displayName = {s(cls, label)};",
             f"    tooltip = {s(cls + '_desc', tip)};", f'    typeName = "{type_name}";',
             f"    defaultValue = {default};", "    class Values {"]
    for i, (value, text) in enumerate(options):
        key = f"{cls}_v{i}"
        v = f'"{value}"' if type_name == "STRING" else value
        lines.append(f"        class V{i} {{ name = {s(key, text)}; value = {v}; }};")
    lines += ["    };", "};"]
    return "\n".join(lines)


SIDES_TIP = "Comma-separated sides: east, west, independent. Empty = all."

EDEN = [
    eden("ROOT_ADS_Module_Settings", "edenSettings", "Detection Settings", 0,
         [setting_attr(n) for n in EDEN_SETTINGS],
         "Mission-wide overrides of the main RADS settings. Hover an attribute for what it does. Every value left on 'Keep setting' (or -1) leaves the CBA setting alone. Sync a trigger to apply the values only when it fires."),
    eden("ROOT_ADS_Module_PursuitSettings", "edenSettings", "Pursuit, Sync & Truce Settings", 0,
         [setting_attr(n) for n in EDEN_PURSUIT],
         "Overrides for suspicion sync between groups, pursuits and checkpoint stops, and safe zone truces. Every value left on 'Keep setting' (or -1, -9999 for the sync radius) leaves the CBA setting alone. Sync a trigger to apply them only when it fires."),
    eden("ROOT_ADS_Module_Zone", "edenZone", "Detection Zone", 1, [
        a_str("ROOT_ADS_Z_label", "Label", "Name shown in Zeus lists and the debug log.", ""),
        a_combo("ROOT_ADS_Z_mode", "Mode", "Multiplier: scale how fast suspicion builds (checkpoints, bases). No cover: disguises do not work (restricted area). Safe haven: no suspicion builds and, with the truce, the AI do not attack players inside.", "NUMBER", 0,
                [(0, "Multiplier"), (1, "No cover (restricted area)"), (2, "Safe haven (truce)")]),
        a_num("ROOT_ADS_Z_build", "Build multiplier", "Multiplier mode: suspicion builds this much faster inside. 2 = twice as fast, 0.5 = half.", 2),
        a_num("ROOT_ADS_Z_decay", "Decay multiplier", "Multiplier mode: suspicion fades this much faster inside.", 1),
        a_str("ROOT_ADS_Z_sides", "Observer sides", "Sides of the AI the zone applies to. " + SIDES_TIP, ""),
        a_num("ROOT_ADS_Z_delay", "Delay (s)", "Seconds after activation before the zone works.", 0),
        a_num("ROOT_ADS_Z_duration", "Duration (s)", "The zone disappears after this long. 0 = permanent.", 0),
        a_num("ROOT_ADS_Z_hourFrom", "Active from hour", "Only active from this time of day (0-24). -1 = always.", -1),
        a_num("ROOT_ADS_Z_hourTo", "Active until hour", "Only active until this time of day (0-24). -1 = always.", -1),
        a_combo("ROOT_ADS_Z_truce", "Truce (safe haven)", "Safe haven only: do the AI hold fire on players inside, even on foot, while they behave?", "NUMBER", -1,
                [(-1, "Use the CBA settings"), (1, "Truce with the options below"), (0, "No truce (only no suspicion)")]),
        a_num("ROOT_ADS_Z_truceStay", "Truce: allowed stay (s)", "How long players may stay before the truce ends. 0 = no limit.", 0),
        a_num("ROOT_ADS_Z_truceWarn", "Truce: warning before the end (s)", "Players are warned this long before their stay runs out.", 60),
        a_bool("ROOT_ADS_Z_truceCareless", "Truce: AI relax", "AI inside the zone are CARELESS and hold fire.", True),
        a_combo("ROOT_ADS_Z_truceScope", "Truce: who loses it", "When one player breaks the truce (shooting, hurting or ramming AI, overstaying)...", "NUMBER", 1,
                [(0, "Only the offender"), (1, "The offender's group"), (2, "Everyone in the zone")]),
        a_bool("ROOT_ADS_Z_truceAim", "Truce: aiming breaks it", "Pointing a weapon at an AI soldier for a few seconds breaks the truce.", False),
    ], "Detection zone in the module's area. Activates at mission start, or when a synced trigger fires (deactivation removes it).",
        extra="canSetArea = 1;\ncanSetAreaShape = 1;\nclass AttributeValues {\n    size3[] = {200, 200, -1};\n    isRectangle = 0;\n};"),
    eden("ROOT_ADS_Module_UnitCover", "edenUnitCover", "Unit Cover Profile", 1, [
        a_combo("ROOT_ADS_U_mode", "Mode", "Normal: usual rules. Exempt: never undercover. Always covered: undercover in any vehicle, ignoring side, heat and zones.", "STRING", '"""normal"""',
                [("normal", "Normal"), ("exempt", "Exempt"), ("force", "Always covered")]),
        a_num("ROOT_ADS_U_mult", "Suspicion multiplier", "How fast the AI grow suspicious of these units. 2 = twice as fast, 0.5 = half.", 1),
        a_num("ROOT_ADS_U_duration", "Duration (s)", "Back to normal after this long. 0 = permanent.", 0),
        a_bool("ROOT_ADS_U_allPlayers", "All players", "Apply to every player (also players joining later) instead of the synced units.", False),
    ], "Cover profile for the synced units (or all players)."),
    eden("ROOT_ADS_Module_Vehicle", "edenVehicle", "Vehicle Disguise", 1, [
        a_combo("ROOT_ADS_V_mode", "Mode", "Auto: by side and settings. Always disguise. Never disguise. Burned: everyone recognises it on sight.", "STRING", '"""disguise"""',
                [("auto", "Auto"), ("disguise", "Always disguise"), ("never", "Never disguise"), ("burned", "Burned (all sides)")]),
        a_str("ROOT_ADS_V_burnSides", "Burned for sides", "Sides that already know this vehicle. " + SIDES_TIP.replace(" Empty = all.", " Empty = none."), ""),
        a_num("ROOT_ADS_V_mult", "Suspicion multiplier", "How suspicious this vehicle looks, replacing the faction multipliers. -1 = by faction/side.", -1),
        a_combo("ROOT_ADS_V_armored", "Armored", "Can the AI see the crew? Armored = only the vehicle can be judged (slow build).", "NUMBER", -1,
                [(-1, "Auto"), (0, "Not armored"), (1, "Armored")]),
        a_num("ROOT_ADS_V_optics", "Optics range (AI crew)", "When enemy AI man this vehicle: range multiplier of its gunner / commander optics. -1 = setting.", -1),
        a_num("ROOT_ADS_V_duration", "Duration (s)", "Back to auto after this long. 0 = permanent.", 0),
    ], "Disguise behaviour for the synced vehicles."),
    eden("ROOT_ADS_Module_GroupProfile", "edenGroupProfile", "AI Group Profile", 0, [
        a_num("ROOT_ADS_G_mult", "Suspicion multiplier", "Vigilance of the synced units' groups: 2-3 = checkpoint guards, 0.5 = sleepy sentries.", 1),
        a_bool("ROOT_ADS_G_immune", "Immune to disguises", "These groups see through every disguise (normal detection).", False),
        a_num("ROOT_ADS_G_shareRadius", "Share radius (m)", "-1 = setting.", -1),
        a_num("ROOT_ADS_G_bulletinChance", "Bulletin chance (0-1)", "-1 = setting.", -1),
        a_combo("ROOT_ADS_G_role", "Role", "Patrol: may chase and stop suspects. Outpost: stays put, still alerts and syncs. Static: never leaves its position.", "STRING", '"""patrol"""',
                [("patrol", "Patrol"), ("outpost", "Outpost"), ("static", "Static")]),
        a_num("ROOT_ADS_G_followThreshold", "Follow threshold (%)", "Suspicion at which these groups start pursuing. -1 = setting.", -1),
        a_num("ROOT_ADS_G_leash", "Roam limit (m)", "How far these groups may go from home while pursuing. 0 = unlimited, -1 = settings (foot / mounted).", -1),
    ], "Observer profile for the groups of the synced AI units."),
    eden("ROOT_ADS_Module_GearReference", "edenGearReference", "Enemy Gear Reference", 0, [
        a_str("ROOT_ADS_R_side", "Observer side", "The side whose expected kit this is: east, west or independent.", "east"),
        a_bool("ROOT_ADS_R_collect", "Collect from that side's AI", "Build the lists from what that side's AI wear 10 s after the start. The lists below are added to it.", True),
        a_str("ROOT_ADS_R_uniform", "Uniforms", "Comma-separated uniform classes they wear.", ""),
        a_str("ROOT_ADS_R_vest", "Vests", "Comma-separated vest classes.", ""),
        a_str("ROOT_ADS_R_headgear", "Headgear", "Comma-separated helmet / hat classes.", ""),
        a_str("ROOT_ADS_R_primary", "Rifles", "Comma-separated primary weapon classes (attachments do not matter).", ""),
        a_str("ROOT_ADS_R_launcher", "Launchers", "Comma-separated launcher classes.", ""),
        a_str("ROOT_ADS_R_backpack", "Backpacks", "Comma-separated backpack classes.", ""),
        a_str("ROOT_ADS_R_facewear", "Facewear", "Comma-separated goggles / facewear classes.", ""),
    ], "What a side's AI expect to see: players wearing the same items build suspicion slower, mismatched items faster (Gear settings: 'How gear is judged'). Tip: the Zeus module of the same name lists everything a side wears, ready to paste here."),
    eden("ROOT_ADS_Module_Compromise", "edenCompromise", "Compromise / Restore Cover", 1, [
        a_combo("ROOT_ADS_C_action", "Action", "Compromise: hostile groups identify the units. Restore: hostile groups forget them.", "NUMBER", 0,
                [(0, "Compromise"), (1, "Restore cover"), (2, "Restore cover + clear burned/wanted")]),
        a_str("ROOT_ADS_C_sides", "Observer sides", SIDES_TIP, ""),
        a_num("ROOT_ADS_C_radius", "Radius (m)", "Only groups within this distance. -1 = unlimited.", -1),
        a_bool("ROOT_ADS_C_allPlayers", "All players", "Apply to every player instead of the synced units.", True),
    ], "Sync a trigger: when it fires, the synced units (or all players) are compromised or get their cover back."),
    eden("ROOT_ADS_Module_Toggle", "edenToggle", "Enable / Disable RADS", 1, [
        a_combo("ROOT_ADS_T_action", "Action", "Turn RADS off or on, or return to the CBA setting.", "NUMBER", 0,
                [(0, "Disable"), (1, "Enable"), (2, "Back to CBA setting")]),
        a_num("ROOT_ADS_T_delay", "Delay (s)", "Seconds after activation.", 0),
        a_num("ROOT_ADS_T_duration", "Duration (s)", "Revert after this long. 0 = permanent.", 0),
    ], "Turns RADS on or off at mission start, after a delay, or when a synced trigger fires."),
    eden("ROOT_ADS_Module_Bulletin", "edenBulletin", "Radio Bulletin", 1, [
        a_str("ROOT_ADS_B_sides", "Receiving sides", "Comma-separated sides: east, west, independent.", "east"),
        a_bool("ROOT_ADS_B_burn", "Burn vehicles", "Synced vehicles (and vehicles of synced units) are recognised on sight.", True),
        a_bool("ROOT_ADS_B_wanted", "Mark wanted", "Synced units are wanted (suspicion builds faster in any vehicle).", True),
        a_bool("ROOT_ADS_B_clear", "Clear instead", "Remove burned / wanted status instead of adding it.", False),
        a_num("ROOT_ADS_B_duration", "Duration (s)", "-1 = setting.", -1),
        a_num("ROOT_ADS_B_range", "Range (m)", "From the module position. 0 = the whole side.", 0),
    ], "Sync units / vehicles (and optionally a trigger): broadcasts them as hostile to the receiving sides."),
]

# ----------------------------------------------------------------------- Zeus dialog strings (LLSTRING in SQF)
ZS = {
    # common
    "msgPlaceVehicle": "Place the module on a vehicle",
    "msgPlaceAI": "Place the module on an AI unit",
    "msgPlaceUnit": "Place the module on a unit or vehicle",
    "msgNoUnits": "No units selected",
    "msgApplied": "RADS settings applied",
    "msgCleared": "RADS overrides cleared",
    "clearOverrides": "Clear these overrides",
    "clearOverrides_desc": "Ignore the values above and return each of these settings to its CBA value.",
    "durationS": "Duration (s)",
    "delayS": "Delay (s)",
    "units": "Units",
    "units_desc": "Sides, groups or players to apply to.",
    "observerSides": "Observer sides",
    "mode": "Mode",
    "action": "Action",
    # settings dialogs
    "settingsTitle": "RADS - Detection Settings (mission override)",
    "syncTitle": "RADS - Suspicion Sync Settings (mission override)",
    "pursuitTitle": "RADS - Pursuit & Checkpoint Settings (mission override)",
    "truceTitle": "RADS - Safe Zone Truce Settings (mission override)",
    # zones
    "zoneTitle": "RADS - Add Detection Zone",
    "zoneLabel": "Label",
    "zoneLabel_desc": "Name shown when removing zones and in the debug log.",
    "zoneMode_desc": "Multiplier: scale suspicion speed (checkpoints, bases). No cover: disguises do not work. Safe haven: no suspicion builds and, with the truce, players inside are not attacked.",
    "zoneMult": "Multiplier (checkpoint / base)",
    "zoneNoCover": "No cover (restricted area)",
    "zoneSafe": "Safe haven (truce)",
    "zoneShape": "Shape",
    "ellipse": "Ellipse",
    "rectangle": "Rectangle",
    "sizeA": "Size A (m)",
    "sizeA_desc": "Radius / half-width.",
    "sizeB": "Size B (m)",
    "sizeB_desc": "Second half-axis. 0 = same as A.",
    "angle": "Angle",
    "buildMult": "Build multiplier",
    "buildMult_desc": "Multiplier mode: suspicion builds this much faster inside. 2 = twice as fast.",
    "decayMult": "Decay multiplier",
    "decayMult_desc": "Multiplier mode: suspicion fades this much faster inside.",
    "zoneSides_desc": "Sides of the AI the zone applies to. None selected = all.",
    "zoneDelay_desc": "The zone becomes active after this long.",
    "zoneDuration_desc": "0 = permanent.",
    "hourFrom": "Active from hour",
    "hourTo": "Active until hour",
    "hour_desc": "Daytime window. -1 = always.",
    "truce": "Truce (safe haven)",
    "truce_desc": "Safe haven only: do the AI hold fire on players inside, even on foot, while they behave?",
    "truceCba": "Use the CBA settings",
    "truceOn": "Truce with the options below",
    "truceOff": "No truce (only no suspicion)",
    "truceStay": "Truce: allowed stay (s)",
    "truceStay_desc": "How long players may stay before the truce ends. 0 = no limit.",
    "truceWarn": "Truce: warning before the end (s)",
    "truceCareless": "Truce: AI relax",
    "truceCareless_desc": "AI inside the zone are CARELESS and hold fire.",
    "truceScope": "Truce: who loses it",
    "truceScope0": "Only the offender",
    "truceScope1": "The offender's group",
    "truceScope2": "Everyone in the zone",
    "truceAim": "Truce: aiming breaks it",
    "zoneAdded": "RADS zone added",
    "removeTitle": "RADS - Remove Detection Zones",
    "remove": "Remove",
    "removeNear": "Zones near this position",
    "removeAll": "All zones",
    "removeRadius": "Near radius (m)",
    "removeRadius_desc": "Zones whose centre is within this radius (first option).",
    "zonesRemoved": "RADS zones removed",
    "noZones": "No RADS zones exist",
    "zoneEntry": "%1 (%2, %3 m away)",
    # unit cover
    "coverTitle": "RADS - Unit Cover Profile",
    "coverMode_desc": "Normal, exempt (never undercover) or always covered (any vehicle, ignores side, heat and zones).",
    "normal": "Normal",
    "exempt": "Exempt",
    "force": "Always covered",
    "suspMult": "Suspicion multiplier",
    "unitMult_desc": "How fast the AI grow suspicious of these units. 2 = twice as fast.",
    "unitDuration_desc": "Back to normal after this long. 0 = permanent.",
    "profileApplied": "RADS profile applied to %1 unit(s)",
    # vehicle
    "vehicleTitle": "RADS - Vehicle Disguise - %1",
    "vehMode_desc": "Auto: by side and settings. Always disguise. Never disguise. Burned: recognised on sight by everyone.",
    "always": "Always disguise",
    "never": "Never disguise",
    "burned": "Burned (all sides)",
    "burnSides": "Burned for sides",
    "burnSides_desc": "Sides that recognise this vehicle on sight (in addition to the mode).",
    "vehMult_desc": "How suspicious this vehicle looks, replacing the faction multipliers. -1 = by faction/side.",
    "armored": "Armored",
    "armored_desc": "Can the AI see the crew? Armored = only the vehicle can be judged (slow build).",
    "notArmored": "Not armored",
    "vehDuration_desc": "Mode / burn revert after this long. 0 = permanent (burn uses the setting).",
    "clearBurned": "Clear burned status",
    "clearBurned_desc": "Forget every side's burn of this vehicle first.",
    "vehicleUpdated": "RADS vehicle updated",
    # group
    "groupTitle": "RADS - AI Group Profile - %1",
    "groupMult_desc": "Vigilance: 2-3 checkpoint guards, 0.5 sleepy sentries.",
    "immune": "Immune to disguises",
    "immune_desc": "This group sees through every disguise (normal detection).",
    "shareRadius": "Share radius (m)",
    "settingDefault": "-1 = setting.",
    "bulletinChance": "Bulletin chance (%)",
    "role": "Role",
    "role_desc": "Patrol: may chase and stop suspects. Outpost: stays put, still alerts and syncs. Static: never leaves its position.",
    "rolePatrol": "Patrol",
    "roleOutpost": "Outpost",
    "roleStatic": "Static",
    "followThreshold": "Follow threshold (%)",
    "followThreshold_desc": "Suspicion at which this group starts pursuing. -1 = setting.",
    "leash": "Roam limit (m)",
    "leash_desc": "How far this group may go from home while pursuing. 0 = unlimited, -1 = settings (foot / mounted).",
    "optics": "Optics range (AI crew)",
    "optics_desc": "When enemy AI man this vehicle: range multiplier of its gunner / commander optics. -1 = setting.",
    "groupApplied": "RADS group profile applied",
    # gear reference
    "gearTitle": "RADS - Enemy Gear Reference",
    "gearSide": "Observer side",
    "gearSide_desc": "The side whose expected kit this is (whose AI compare players against it).",
    "gearStart": "Start from",
    "gearStart_desc": "Current list: edit what is set. Collect: fill the lists with everything that side's AI wear now.",
    "gearCurrent": "Current list",
    "gearCollect": "Collect from that side's AI now",
    "gearClear": "Clear the list",
    "gearEditTitle": "RADS - Enemy Gear Reference - %1",
    "gearUniform": "Uniforms",
    "gearVest": "Vests",
    "gearHeadgear": "Headgear",
    "gearPrimary": "Rifles",
    "gearLauncher": "Launchers",
    "gearBackpack": "Backpacks",
    "gearFacewear": "Facewear",
    "gearList_desc": "Comma-separated classes. Paste into the 3DEN Enemy Gear Reference module to reuse.",
    "gearCopy": "Copy to clipboard",
    "gearCopy_desc": "Copies all seven lists (also written to the RPT). Clipboard access may be blocked in multiplayer.",
    "gearApplied": "RADS gear reference for %1 applied",
    "gearClearedMsg": "RADS gear reference for %1 cleared",
    # pursuit
    "pursuitOrderTitle": "RADS - Order Pursuit - %1",
    "pursuitTarget": "Target",
    "pursuitTarget_desc": "Undercover unit to chase (on foot) or follow and stop (mounted), then inspect.",
    "pursuitCallOff": "Call off the current pursuit",
    "pursuitNoTargets": "Nobody is undercover",
    "pursuitOrdered": "RADS pursuit ordered",
    "pursuitStopped": "RADS pursuit called off",
    # compromise / toggle / bulletin
    "compromiseTitle": "RADS - Compromise / Restore Cover",
    "compromise": "Compromise (hostile AI identify them)",
    "restore": "Restore cover (hostile AI forget them)",
    "restoreClear": "Restore cover + clear burned/wanted",
    "compromiseSides_desc": "Compromise only: sides that identify. None = all hostile.",
    "radius": "Radius (m)",
    "compromiseRadius_desc": "Compromise only: groups within this distance of each unit. 0 = unlimited.",
    "compromiseDone": "RADS: %1 unit(s) %2",
    "compromised": "compromised",
    "restored": "restored",
    "toggleTitle": "RADS - Enable / Disable",
    "disable": "Disable",
    "enable": "Enable",
    "backToCba": "Back to CBA setting",
    "toggleDelay_desc": "Apply after this long.",
    "toggleDuration_desc": "Revert after this long. 0 = permanent.",
    "toggleDone": "RADS toggle scheduled",
    "bulletinTitle": "RADS - Radio Bulletin",
    "broadcast": "Broadcast",
    "clearStatus": "Clear burned/wanted",
    "receivingSides": "Receiving sides",
    "receivingSides_desc": "Sides that hear the bulletin (or that are cleared). None = all.",
    "burnVehicle": "Burn vehicle",
    "burnVehicle_desc": "The vehicle is recognised on sight.",
    "markWanted": "Mark crew wanted",
    "markWanted_desc": "Covered units build suspicion faster in any vehicle.",
    "alertArea": "Alert the area",
    "alertArea_desc": "Groups near this position start searching.",
    "bulletinDuration_desc": "0 = settings.",
    "range": "Range (m)",
    "bulletinRange_desc": "Only groups within this distance know. 0 = the whole side.",
    "bulletinCleared": "RADS status cleared",
    "bulletinSent": "RADS bulletin broadcast",
    # inspect
    "inspectTitle": "RADS - covered players",
    "inspectLine": "%1: max %2, identified by %3%4",
    "inspectWanted": "(wanted)",
    "inspectNobody": "Nobody is undercover.",
    "inspectNote": "Values refresh on state changes (enable 'Publish suspicion live' for live values).",
}
for k, v in ZS.items():
    STR[k] = v

# ----------------------------------------------------------------------- output
HEADER = r'''// Generated by tools/gen_modules.py - edit the definitions there, not this file.
#define ZEUS_MODULE(cls,fnc,name) \
    class cls: zen_modules_moduleBase { \
        author = "Root"; \
        _generalMacro = QUOTE(cls); \
        category = "ROOT_ADS"; \
        function = QFUNC(fnc); \
        displayName = name; \
        curatorCanAttach = 1; \
    }

#define ATTR_NUM_RAW(cls,label,tip,def) \
    class cls: Edit { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "NUMBER"; \
        defaultValue = def; \
    }
#define ATTR_NUM(cls,label,tip,def) ATTR_NUM_RAW(cls,label,tip,def)

#define ATTR_STR(cls,label,tip,def) \
    class cls: Edit { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "STRING"; \
        defaultValue = def; \
    }

#define ATTR_BOOL(cls,label,tip,def) \
    class cls: Checkbox { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "BOOL"; \
        defaultValue = QUOTE(def); \
    }

// Keep / Off / On for boolean setting overrides
#define ATTR_TRI_RAW(cls,label,tip) \
    class cls: Combo { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "NUMBER"; \
        defaultValue = -1; \
        class Values { \
            class Keep { name = CSTRING(keepSetting); value = -1; }; \
            class Off { name = CSTRING(off); value = 0; }; \
            class On { name = CSTRING(on); value = 1; }; \
        }; \
    }
#define ATTR_TRI(cls,label,tip) ATTR_TRI_RAW(cls,label,tip)

#define EDEN_MODULE_BASE(name,fnc,trigger) \
    scope = 2; \
    scopeCurator = 0; \
    author = "Root"; \
    displayName = name; \
    category = "ROOT_ADS"; \
    function = QFUNC(fnc); \
    functionPriority = 1; \
    isGlobal = 0; \
    isTriggerActivated = trigger; \
    isDisposable = 0; \
    is3DEN = 0; \
    icon = "\a3\ui_f\data\igui\cfg\simpletasks\types\scout_ca.paa"
'''


def build_cfg():
    out = [HEADER, "class CfgVehicles {", "    // ------------------------------------------------------------------ Zeus (ZEN)",
           "    class zen_modules_moduleBase;", ""]
    for cls, fnc, _name in ZEUS:
        out.append(f"    ZEUS_MODULE({cls},{fnc},CSTRING(zeus_{cls}));")
    out += ["", "    // ------------------------------------------------------------------ 3DEN",
            "    class Logic;", "    class Module_F: Logic {", "        class AttributesBase {", "            class Edit;",
            "            class Combo;", "            class Checkbox;", "            class ModuleDescription;", "        };",
            "        class ModuleDescription;", "    };"]
    for m in EDEN:
        out += ["", f"    class {m['cls']}: Module_F {{", f"        EDEN_MODULE_BASE({m['name']},{m['fnc']},{m['trigger']});"]
        if m["extra"]:
            out.append(indent(m["extra"], 8))
        out.append("        class Attributes: AttributesBase {")
        for a in m["attrs"]:
            out.append(indent(a, 12))
        out += ["            class ModuleDescription: ModuleDescription {};", "        };",
                "        class ModuleDescription: ModuleDescription {", f"            description = {m['desc']};", "        };", "    };"]
    out.append("};")
    return "\n".join(out) + "\n"


def build_xml():
    out = ['<?xml version="1.0" encoding="utf-8"?>', '<Project name="root_ads">', '    <Package name="modules">']
    for k in sorted(STR, key=str.lower):
        out.append(f'        <Key ID="STR_root_ads_modules_{k}">')
        out.append(f'            <English>{html.escape(STR[k], quote=False)}</English>')
        out.append('        </Key>')
    out += ['    </Package>', '</Project>']
    return "\n".join(out) + "\n"


def write(rel, text):
    with open(os.path.join(ROOT, rel), "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", rel)


if __name__ == "__main__":
    for n in EDEN_SETTINGS + EDEN_PURSUIT:
        assert n in SETTINGS, n
    cfg = build_cfg()
    write("addons/modules/CfgVehicles.hpp", cfg)
    write("addons/modules/stringtable.xml", build_xml())
    units = [c for c, _, _ in ZEUS] + [m["cls"] for m in EDEN]
    print("units[]:", ", ".join(f'"{u}"' for u in units))
