// Generated by tools/gen_modules.py - edit the definitions there, not this file.
#define ZEUS_MODULE(cls,fnc,name) \
    class cls: zen_modules_moduleBase { \
        author = "Root"; \
        _generalMacro = QUOTE(cls); \
        category = "ROOT_ADS"; \
        function = QFUNC(fnc); \
        displayName = name; \
        curatorCanAttach = 1; \
    }

#define ATTR_NUM_RAW(cls,label,tip,def) \
    class cls: Edit { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "NUMBER"; \
        defaultValue = def; \
    }
#define ATTR_NUM(cls,label,tip,def) ATTR_NUM_RAW(cls,label,tip,def)

#define ATTR_STR(cls,label,tip,def) \
    class cls: Edit { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "STRING"; \
        defaultValue = def; \
    }

#define ATTR_BOOL(cls,label,tip,def) \
    class cls: Checkbox { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "BOOL"; \
        defaultValue = QUOTE(def); \
    }

// Keep / Off / On for boolean setting overrides
#define ATTR_TRI_RAW(cls,label,tip) \
    class cls: Combo { \
        property = QUOTE(cls); \
        displayName = label; \
        tooltip = tip; \
        typeName = "NUMBER"; \
        defaultValue = -1; \
        class Values { \
            class Keep { name = CSTRING(keepSetting); value = -1; }; \
            class Off { name = CSTRING(off); value = 0; }; \
            class On { name = CSTRING(on); value = 1; }; \
        }; \
    }
#define ATTR_TRI(cls,label,tip) ATTR_TRI_RAW(cls,label,tip)

#define EDEN_MODULE_BASE(name,fnc,trigger) \
    scope = 2; \
    scopeCurator = 0; \
    author = "Root"; \
    displayName = name; \
    category = "ROOT_ADS"; \
    function = QFUNC(fnc); \
    functionPriority = 1; \
    isGlobal = 0; \
    isTriggerActivated = trigger; \
    isDisposable = 0; \
    is3DEN = 0; \
    icon = "\a3\ui_f\data\igui\cfg\simpletasks\types\scout_ca.paa"

class CfgVehicles {
    // ------------------------------------------------------------------ Zeus (ZEN)
    class zen_modules_moduleBase;

    ZEUS_MODULE(ROOT_ADS_Zeus_Settings,zeusSettings,CSTRING(zeus_ROOT_ADS_Zeus_Settings));
    ZEUS_MODULE(ROOT_ADS_Zeus_SyncSettings,zeusSyncSettings,CSTRING(zeus_ROOT_ADS_Zeus_SyncSettings));
    ZEUS_MODULE(ROOT_ADS_Zeus_PursuitSettings,zeusPursuitSettings,CSTRING(zeus_ROOT_ADS_Zeus_PursuitSettings));
    ZEUS_MODULE(ROOT_ADS_Zeus_TruceSettings,zeusTruceSettings,CSTRING(zeus_ROOT_ADS_Zeus_TruceSettings));
    ZEUS_MODULE(ROOT_ADS_Zeus_AddZone,zeusAddZone,CSTRING(zeus_ROOT_ADS_Zeus_AddZone));
    ZEUS_MODULE(ROOT_ADS_Zeus_RemoveZones,zeusRemoveZones,CSTRING(zeus_ROOT_ADS_Zeus_RemoveZones));
    ZEUS_MODULE(ROOT_ADS_Zeus_UnitCover,zeusUnitCover,CSTRING(zeus_ROOT_ADS_Zeus_UnitCover));
    ZEUS_MODULE(ROOT_ADS_Zeus_Vehicle,zeusVehicle,CSTRING(zeus_ROOT_ADS_Zeus_Vehicle));
    ZEUS_MODULE(ROOT_ADS_Zeus_GroupProfile,zeusGroupProfile,CSTRING(zeus_ROOT_ADS_Zeus_GroupProfile));
    ZEUS_MODULE(ROOT_ADS_Zeus_GearReference,zeusGearReference,CSTRING(zeus_ROOT_ADS_Zeus_GearReference));
    ZEUS_MODULE(ROOT_ADS_Zeus_OrderPursuit,zeusOrderPursuit,CSTRING(zeus_ROOT_ADS_Zeus_OrderPursuit));
    ZEUS_MODULE(ROOT_ADS_Zeus_Compromise,zeusCompromise,CSTRING(zeus_ROOT_ADS_Zeus_Compromise));
    ZEUS_MODULE(ROOT_ADS_Zeus_Toggle,zeusToggle,CSTRING(zeus_ROOT_ADS_Zeus_Toggle));
    ZEUS_MODULE(ROOT_ADS_Zeus_Bulletin,zeusBulletin,CSTRING(zeus_ROOT_ADS_Zeus_Bulletin));
    ZEUS_MODULE(ROOT_ADS_Zeus_Inspect,zeusInspect,CSTRING(zeus_ROOT_ADS_Zeus_Inspect));

    // ------------------------------------------------------------------ 3DEN
    class Logic;
    class Module_F: Logic {
        class AttributesBase {
            class Edit;
            class Combo;
            class Checkbox;
            class ModuleDescription;
        };
        class ModuleDescription;
    };

    class ROOT_ADS_Module_Settings: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_Settings),edenSettings,0);
        class Attributes: AttributesBase {
            ATTR_TRI_RAW(ROOT_ADS_S_enabled,"$STR_root_ads_main_enabled","$STR_root_ads_main_enabled_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_buildRate,"$STR_root_ads_main_buildRate","$STR_root_ads_main_buildRate_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_decayRate,"$STR_root_ads_main_decayRate","$STR_root_ads_main_decayRate_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_suspiciousThreshold,"$STR_root_ads_main_suspiciousThreshold","$STR_root_ads_main_suspiciousThreshold_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_identifyThreshold,"$STR_root_ads_main_identifyThreshold","$STR_root_ads_main_identifyThreshold_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_maxRange,"$STR_root_ads_main_maxRange","$STR_root_ads_main_maxRange_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_identifyRange,"$STR_root_ads_main_identifyRange","$STR_root_ads_main_identifyRange_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_instantRange,"$STR_root_ads_main_instantRange","$STR_root_ads_main_instantRange_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_forgetAfter,"$STR_root_ads_main_forgetAfter","$STR_root_ads_main_forgetAfter_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_memoryTime,"$STR_root_ads_main_memoryTime","$STR_root_ads_main_memoryTime_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_heatDuration,"$STR_root_ads_main_heatDuration","$STR_root_ads_main_heatDuration_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_firedRadius,"$STR_root_ads_main_firedRadius","$STR_root_ads_main_firedRadius_desc",-1);
            class ROOT_ADS_S_allowHostileVeh: Combo {
                property = "ROOT_ADS_S_allowHostileVeh";
                displayName = "$STR_root_ads_main_allowHostileVeh";
                tooltip = "$STR_root_ads_main_allowHostileVeh_desc";
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class Keep { name = CSTRING(keepSetting); value = -1; };
                    class V0 { name = "$STR_root_ads_main_allowHostileVeh_opt0"; value = 0; };
                    class V1 { name = "$STR_root_ads_main_allowHostileVeh_opt1"; value = 1; };
                    class V2 { name = "$STR_root_ads_main_allowHostileVeh_opt2"; value = 2; };
                };
            };
            ATTR_NUM_RAW(ROOT_ADS_S_sameFactionVehMult,"$STR_root_ads_main_sameFactionVehMult","$STR_root_ads_main_sameFactionVehMult_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_hostileVehMult,"$STR_root_ads_main_hostileVehMult","$STR_root_ads_main_hostileVehMult_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_armoredDetect,"$STR_root_ads_main_armoredDetect","$STR_root_ads_main_armoredDetect_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_armoredHullMult,"$STR_root_ads_main_armoredHullMult","$STR_root_ads_main_armoredHullMult_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_armoredDrivingOnly,"$STR_root_ads_main_armoredDrivingOnly","$STR_root_ads_main_armoredDrivingOnly_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_vehOpticsEnabled,"$STR_root_ads_main_vehOpticsEnabled","$STR_root_ads_main_vehOpticsEnabled_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_vehOpticsMult,"$STR_root_ads_main_vehOpticsMult","$STR_root_ads_main_vehOpticsMult_desc",-1);
            class ROOT_ADS_S_gearCompareMode: Combo {
                property = "ROOT_ADS_S_gearCompareMode";
                displayName = "$STR_root_ads_main_gearCompareMode";
                tooltip = "$STR_root_ads_main_gearCompareMode_desc";
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class Keep { name = CSTRING(keepSetting); value = -1; };
                    class V0 { name = "$STR_root_ads_main_gearCompareMode_opt0"; value = 0; };
                    class V1 { name = "$STR_root_ads_main_gearCompareMode_opt1"; value = 1; };
                    class V2 { name = "$STR_root_ads_main_gearCompareMode_opt2"; value = 2; };
                    class V3 { name = "$STR_root_ads_main_gearCompareMode_opt3"; value = 3; };
                };
            };
            class ROOT_ADS_S_gearRefSource: Combo {
                property = "ROOT_ADS_S_gearRefSource";
                displayName = "$STR_root_ads_main_gearRefSource";
                tooltip = "$STR_root_ads_main_gearRefSource_desc";
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class Keep { name = CSTRING(keepSetting); value = -1; };
                    class V0 { name = "$STR_root_ads_main_gearRefSource_opt0"; value = 0; };
                    class V1 { name = "$STR_root_ads_main_gearRefSource_opt1"; value = 1; };
                    class V2 { name = "$STR_root_ads_main_gearRefSource_opt2"; value = 2; };
                };
            };
            ATTR_TRI_RAW(ROOT_ADS_S_metaDetect,"$STR_root_ads_main_metaDetect","$STR_root_ads_main_metaDetect_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_metaMaxSpeed,"$STR_root_ads_main_metaMaxSpeed","$STR_root_ads_main_metaMaxSpeed_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_hiddenCrewAny,"$STR_root_ads_main_hiddenCrewAny","$STR_root_ads_main_hiddenCrewAny_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_reverseMult,"$STR_root_ads_main_reverseMult","$STR_root_ads_main_reverseMult_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_rearFacingMult,"$STR_root_ads_main_rearFacingMult","$STR_root_ads_main_rearFacingMult_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_ramCompromise,"$STR_root_ads_main_ramCompromise","$STR_root_ads_main_ramCompromise_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_ramBurn,"$STR_root_ads_main_ramBurn","$STR_root_ads_main_ramBurn_desc");
            class ROOT_ADS_S_convoyMode: Combo {
                property = "ROOT_ADS_S_convoyMode";
                displayName = "$STR_root_ads_main_convoyMode";
                tooltip = "$STR_root_ads_main_convoyMode_desc";
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class Keep { name = CSTRING(keepSetting); value = -1; };
                    class V0 { name = "$STR_root_ads_main_convoyMode_opt0"; value = 0; };
                    class V1 { name = "$STR_root_ads_main_convoyMode_opt1"; value = 1; };
                    class V2 { name = "$STR_root_ads_main_convoyMode_opt2"; value = 2; };
                };
            };
            ATTR_NUM_RAW(ROOT_ADS_S_convoySpillSusp,"$STR_root_ads_main_convoySpillSusp","$STR_root_ads_main_convoySpillSusp_desc",-1);
            class ROOT_ADS_S_shareMode: Combo {
                property = "ROOT_ADS_S_shareMode";
                displayName = "$STR_root_ads_main_shareMode";
                tooltip = "$STR_root_ads_main_shareMode_desc";
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class Keep { name = CSTRING(keepSetting); value = -1; };
                    class V0 { name = "$STR_root_ads_main_shareMode_opt0"; value = 0; };
                    class V1 { name = "$STR_root_ads_main_shareMode_opt1"; value = 1; };
                    class V2 { name = "$STR_root_ads_main_shareMode_opt2"; value = 2; };
                };
            };
            ATTR_NUM_RAW(ROOT_ADS_S_shareRadius,"$STR_root_ads_main_shareRadius","$STR_root_ads_main_shareRadius_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_bulletinEnabled,"$STR_root_ads_main_bulletinEnabled","$STR_root_ads_main_bulletinEnabled_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_bulletinChance,"$STR_root_ads_main_bulletinChance","$STR_root_ads_main_bulletinChance_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_bulletinRange,"$STR_root_ads_main_bulletinRange","$STR_root_ads_main_bulletinRange_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_burnDuration,"$STR_root_ads_main_burnDuration","$STR_root_ads_main_burnDuration_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_wantedDuration,"$STR_root_ads_main_wantedDuration","$STR_root_ads_main_wantedDuration_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_informantsEnabled,"$STR_root_ads_main_informantsEnabled","$STR_root_ads_main_informantsEnabled_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_theftEnabled,"$STR_root_ads_main_theftEnabled","$STR_root_ads_main_theftEnabled_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_aiAware,"$STR_root_ads_main_aiAware","$STR_root_ads_main_aiAware_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_aiWatch,"$STR_root_ads_main_aiWatch","$STR_root_ads_main_aiWatch_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_aiGlance,"$STR_root_ads_main_aiGlance","$STR_root_ads_main_aiGlance_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_aiLook,"$STR_root_ads_main_aiLook","$STR_root_ads_main_aiLook_desc");
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_Settings_desc);
        };
    };

    class ROOT_ADS_Module_PursuitSettings: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_PursuitSettings),edenSettings,0);
        class Attributes: AttributesBase {
            ATTR_TRI_RAW(ROOT_ADS_S_syncEnabled,"$STR_root_ads_main_syncEnabled","$STR_root_ads_main_syncEnabled_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_syncRadius,"$STR_root_ads_main_syncRadius","$STR_root_ads_main_syncRadius_desc",-9999);
            ATTR_NUM_RAW(ROOT_ADS_S_syncDelay,"$STR_root_ads_main_syncDelay","$STR_root_ads_main_syncDelay_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_syncFactor,"$STR_root_ads_main_syncFactor","$STR_root_ads_main_syncFactor_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_syncMin,"$STR_root_ads_main_syncMin","$STR_root_ads_main_syncMin_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_syncCanIdentify,"$STR_root_ads_main_syncCanIdentify","$STR_root_ads_main_syncCanIdentify_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_syncRespectSig,"$STR_root_ads_main_syncRespectSig","$STR_root_ads_main_syncRespectSig_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_appearanceChangeKeep,"$STR_root_ads_main_appearanceChangeKeep","$STR_root_ads_main_appearanceChangeKeep_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_pursuitEnabled,"$STR_root_ads_main_pursuitEnabled","$STR_root_ads_main_pursuitEnabled_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_followEnabled,"$STR_root_ads_main_followEnabled","$STR_root_ads_main_followEnabled_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_followThreshold,"$STR_root_ads_main_followThreshold","$STR_root_ads_main_followThreshold_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_pursuitMaxGroups,"$STR_root_ads_main_pursuitMaxGroups","$STR_root_ads_main_pursuitMaxGroups_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_pursuitMaxTime,"$STR_root_ads_main_pursuitMaxTime","$STR_root_ads_main_pursuitMaxTime_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_leashEnabled,"$STR_root_ads_main_leashEnabled","$STR_root_ads_main_leashEnabled_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_leashFoot,"$STR_root_ads_main_leashFoot","$STR_root_ads_main_leashFoot_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_leashVehicle,"$STR_root_ads_main_leashVehicle","$STR_root_ads_main_leashVehicle_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_leashGiveUp,"$STR_root_ads_main_leashGiveUp","$STR_root_ads_main_leashGiveUp_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_followDistance,"$STR_root_ads_main_followDistance","$STR_root_ads_main_followDistance_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_stopTimeout,"$STR_root_ads_main_stopTimeout","$STR_root_ads_main_stopTimeout_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_stopSignalHorn,"$STR_root_ads_main_stopSignalHorn","$STR_root_ads_main_stopSignalHorn_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_stopSignalLights,"$STR_root_ads_main_stopSignalLights","$STR_root_ads_main_stopSignalLights_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_alertRadius,"$STR_root_ads_main_alertRadius","$STR_root_ads_main_alertRadius_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_alertSuspicion,"$STR_root_ads_main_alertSuspicion","$STR_root_ads_main_alertSuspicion_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_inspectTime,"$STR_root_ads_main_inspectTime","$STR_root_ads_main_inspectTime_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_inspectMult,"$STR_root_ads_main_inspectMult","$STR_root_ads_main_inspectMult_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_inspectClearSusp,"$STR_root_ads_main_inspectClearSusp","$STR_root_ads_main_inspectClearSusp_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_fleeDistance,"$STR_root_ads_main_fleeDistance","$STR_root_ads_main_fleeDistance_desc",-1);
            class ROOT_ADS_S_fleeBulletin: Combo {
                property = "ROOT_ADS_S_fleeBulletin";
                displayName = "$STR_root_ads_main_fleeBulletin";
                tooltip = "$STR_root_ads_main_fleeBulletin_desc";
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class Keep { name = CSTRING(keepSetting); value = -1; };
                    class V0 { name = "$STR_root_ads_main_fleeBulletin_opt0"; value = 0; };
                    class V1 { name = "$STR_root_ads_main_fleeBulletin_opt1"; value = 1; };
                    class V2 { name = "$STR_root_ads_main_fleeBulletin_opt2"; value = 2; };
                };
            };
            ATTR_TRI_RAW(ROOT_ADS_S_fleeBurn,"$STR_root_ads_main_fleeBurn","$STR_root_ads_main_fleeBurn_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_lambsDisableDuringPursuit,"$STR_root_ads_main_lambsDisableDuringPursuit","$STR_root_ads_main_lambsDisableDuringPursuit_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_lambsHuntOnCompromise,"$STR_root_ads_main_lambsHuntOnCompromise","$STR_root_ads_main_lambsHuntOnCompromise_desc");
            ATTR_TRI_RAW(ROOT_ADS_S_truceEnabled,"$STR_root_ads_main_truceEnabled","$STR_root_ads_main_truceEnabled_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_truceMaxStay,"$STR_root_ads_main_truceMaxStay","$STR_root_ads_main_truceMaxStay_desc",-1);
            ATTR_NUM_RAW(ROOT_ADS_S_truceWarn,"$STR_root_ads_main_truceWarn","$STR_root_ads_main_truceWarn_desc",-1);
            ATTR_TRI_RAW(ROOT_ADS_S_truceCareless,"$STR_root_ads_main_truceCareless","$STR_root_ads_main_truceCareless_desc");
            class ROOT_ADS_S_truceBreakScope: Combo {
                property = "ROOT_ADS_S_truceBreakScope";
                displayName = "$STR_root_ads_main_truceBreakScope";
                tooltip = "$STR_root_ads_main_truceBreakScope_desc";
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class Keep { name = CSTRING(keepSetting); value = -1; };
                    class V0 { name = "$STR_root_ads_main_truceBreakScope_opt0"; value = 0; };
                    class V1 { name = "$STR_root_ads_main_truceBreakScope_opt1"; value = 1; };
                    class V2 { name = "$STR_root_ads_main_truceBreakScope_opt2"; value = 2; };
                };
            };
            ATTR_TRI_RAW(ROOT_ADS_S_truceBreakOnAim,"$STR_root_ads_main_truceBreakOnAim","$STR_root_ads_main_truceBreakOnAim_desc");
            ATTR_NUM_RAW(ROOT_ADS_S_truceCooldown,"$STR_root_ads_main_truceCooldown","$STR_root_ads_main_truceCooldown_desc",-1);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_PursuitSettings_desc);
        };
    };

    class ROOT_ADS_Module_Zone: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_Zone),edenZone,1);
        canSetArea = 1;
        canSetAreaShape = 1;
        class AttributeValues {
            size3[] = {200, 200, -1};
            isRectangle = 0;
        };
        class Attributes: AttributesBase {
            ATTR_STR(ROOT_ADS_Z_label,CSTRING(ROOT_ADS_Z_label),CSTRING(ROOT_ADS_Z_label_desc),"""""");
            class ROOT_ADS_Z_mode: Combo {
                property = "ROOT_ADS_Z_mode";
                displayName = CSTRING(ROOT_ADS_Z_mode);
                tooltip = CSTRING(ROOT_ADS_Z_mode_desc);
                typeName = "NUMBER";
                defaultValue = 0;
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_Z_mode_v0); value = 0; };
                    class V1 { name = CSTRING(ROOT_ADS_Z_mode_v1); value = 1; };
                    class V2 { name = CSTRING(ROOT_ADS_Z_mode_v2); value = 2; };
                };
            };
            ATTR_NUM(ROOT_ADS_Z_build,CSTRING(ROOT_ADS_Z_build),CSTRING(ROOT_ADS_Z_build_desc),2);
            ATTR_NUM(ROOT_ADS_Z_decay,CSTRING(ROOT_ADS_Z_decay),CSTRING(ROOT_ADS_Z_decay_desc),1);
            ATTR_STR(ROOT_ADS_Z_sides,CSTRING(ROOT_ADS_Z_sides),CSTRING(ROOT_ADS_Z_sides_desc),"""""");
            ATTR_NUM(ROOT_ADS_Z_delay,CSTRING(ROOT_ADS_Z_delay),CSTRING(ROOT_ADS_Z_delay_desc),0);
            ATTR_NUM(ROOT_ADS_Z_duration,CSTRING(ROOT_ADS_Z_duration),CSTRING(ROOT_ADS_Z_duration_desc),0);
            ATTR_NUM(ROOT_ADS_Z_hourFrom,CSTRING(ROOT_ADS_Z_hourFrom),CSTRING(ROOT_ADS_Z_hourFrom_desc),-1);
            ATTR_NUM(ROOT_ADS_Z_hourTo,CSTRING(ROOT_ADS_Z_hourTo),CSTRING(ROOT_ADS_Z_hourTo_desc),-1);
            class ROOT_ADS_Z_truce: Combo {
                property = "ROOT_ADS_Z_truce";
                displayName = CSTRING(ROOT_ADS_Z_truce);
                tooltip = CSTRING(ROOT_ADS_Z_truce_desc);
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_Z_truce_v0); value = -1; };
                    class V1 { name = CSTRING(ROOT_ADS_Z_truce_v1); value = 1; };
                    class V2 { name = CSTRING(ROOT_ADS_Z_truce_v2); value = 0; };
                };
            };
            ATTR_NUM(ROOT_ADS_Z_truceStay,CSTRING(ROOT_ADS_Z_truceStay),CSTRING(ROOT_ADS_Z_truceStay_desc),0);
            ATTR_NUM(ROOT_ADS_Z_truceWarn,CSTRING(ROOT_ADS_Z_truceWarn),CSTRING(ROOT_ADS_Z_truceWarn_desc),60);
            ATTR_BOOL(ROOT_ADS_Z_truceCareless,CSTRING(ROOT_ADS_Z_truceCareless),CSTRING(ROOT_ADS_Z_truceCareless_desc),true);
            class ROOT_ADS_Z_truceScope: Combo {
                property = "ROOT_ADS_Z_truceScope";
                displayName = CSTRING(ROOT_ADS_Z_truceScope);
                tooltip = CSTRING(ROOT_ADS_Z_truceScope_desc);
                typeName = "NUMBER";
                defaultValue = 1;
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_Z_truceScope_v0); value = 0; };
                    class V1 { name = CSTRING(ROOT_ADS_Z_truceScope_v1); value = 1; };
                    class V2 { name = CSTRING(ROOT_ADS_Z_truceScope_v2); value = 2; };
                };
            };
            ATTR_BOOL(ROOT_ADS_Z_truceAim,CSTRING(ROOT_ADS_Z_truceAim),CSTRING(ROOT_ADS_Z_truceAim_desc),false);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_Zone_desc);
        };
    };

    class ROOT_ADS_Module_UnitCover: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_UnitCover),edenUnitCover,1);
        class Attributes: AttributesBase {
            class ROOT_ADS_U_mode: Combo {
                property = "ROOT_ADS_U_mode";
                displayName = CSTRING(ROOT_ADS_U_mode);
                tooltip = CSTRING(ROOT_ADS_U_mode_desc);
                typeName = "STRING";
                defaultValue = """normal""";
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_U_mode_v0); value = "normal"; };
                    class V1 { name = CSTRING(ROOT_ADS_U_mode_v1); value = "exempt"; };
                    class V2 { name = CSTRING(ROOT_ADS_U_mode_v2); value = "force"; };
                };
            };
            ATTR_NUM(ROOT_ADS_U_mult,CSTRING(ROOT_ADS_U_mult),CSTRING(ROOT_ADS_U_mult_desc),1);
            ATTR_NUM(ROOT_ADS_U_duration,CSTRING(ROOT_ADS_U_duration),CSTRING(ROOT_ADS_U_duration_desc),0);
            ATTR_BOOL(ROOT_ADS_U_allPlayers,CSTRING(ROOT_ADS_U_allPlayers),CSTRING(ROOT_ADS_U_allPlayers_desc),false);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_UnitCover_desc);
        };
    };

    class ROOT_ADS_Module_Vehicle: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_Vehicle),edenVehicle,1);
        class Attributes: AttributesBase {
            class ROOT_ADS_V_mode: Combo {
                property = "ROOT_ADS_V_mode";
                displayName = CSTRING(ROOT_ADS_V_mode);
                tooltip = CSTRING(ROOT_ADS_V_mode_desc);
                typeName = "STRING";
                defaultValue = """disguise""";
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_V_mode_v0); value = "auto"; };
                    class V1 { name = CSTRING(ROOT_ADS_V_mode_v1); value = "disguise"; };
                    class V2 { name = CSTRING(ROOT_ADS_V_mode_v2); value = "never"; };
                    class V3 { name = CSTRING(ROOT_ADS_V_mode_v3); value = "burned"; };
                };
            };
            ATTR_STR(ROOT_ADS_V_burnSides,CSTRING(ROOT_ADS_V_burnSides),CSTRING(ROOT_ADS_V_burnSides_desc),"""""");
            ATTR_NUM(ROOT_ADS_V_mult,CSTRING(ROOT_ADS_V_mult),CSTRING(ROOT_ADS_V_mult_desc),-1);
            class ROOT_ADS_V_armored: Combo {
                property = "ROOT_ADS_V_armored";
                displayName = CSTRING(ROOT_ADS_V_armored);
                tooltip = CSTRING(ROOT_ADS_V_armored_desc);
                typeName = "NUMBER";
                defaultValue = -1;
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_V_armored_v0); value = -1; };
                    class V1 { name = CSTRING(ROOT_ADS_V_armored_v1); value = 0; };
                    class V2 { name = CSTRING(ROOT_ADS_V_armored_v2); value = 1; };
                };
            };
            ATTR_NUM(ROOT_ADS_V_optics,CSTRING(ROOT_ADS_V_optics),CSTRING(ROOT_ADS_V_optics_desc),-1);
            ATTR_NUM(ROOT_ADS_V_duration,CSTRING(ROOT_ADS_V_duration),CSTRING(ROOT_ADS_V_duration_desc),0);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_Vehicle_desc);
        };
    };

    class ROOT_ADS_Module_GroupProfile: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_GroupProfile),edenGroupProfile,0);
        class Attributes: AttributesBase {
            ATTR_NUM(ROOT_ADS_G_mult,CSTRING(ROOT_ADS_G_mult),CSTRING(ROOT_ADS_G_mult_desc),1);
            ATTR_BOOL(ROOT_ADS_G_immune,CSTRING(ROOT_ADS_G_immune),CSTRING(ROOT_ADS_G_immune_desc),false);
            ATTR_NUM(ROOT_ADS_G_shareRadius,CSTRING(ROOT_ADS_G_shareRadius),CSTRING(ROOT_ADS_G_shareRadius_desc),-1);
            ATTR_NUM(ROOT_ADS_G_bulletinChance,CSTRING(ROOT_ADS_G_bulletinChance),CSTRING(ROOT_ADS_G_bulletinChance_desc),-1);
            class ROOT_ADS_G_role: Combo {
                property = "ROOT_ADS_G_role";
                displayName = CSTRING(ROOT_ADS_G_role);
                tooltip = CSTRING(ROOT_ADS_G_role_desc);
                typeName = "STRING";
                defaultValue = """patrol""";
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_G_role_v0); value = "patrol"; };
                    class V1 { name = CSTRING(ROOT_ADS_G_role_v1); value = "outpost"; };
                    class V2 { name = CSTRING(ROOT_ADS_G_role_v2); value = "static"; };
                };
            };
            ATTR_NUM(ROOT_ADS_G_followThreshold,CSTRING(ROOT_ADS_G_followThreshold),CSTRING(ROOT_ADS_G_followThreshold_desc),-1);
            ATTR_NUM(ROOT_ADS_G_leash,CSTRING(ROOT_ADS_G_leash),CSTRING(ROOT_ADS_G_leash_desc),-1);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_GroupProfile_desc);
        };
    };

    class ROOT_ADS_Module_GearReference: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_GearReference),edenGearReference,0);
        class Attributes: AttributesBase {
            ATTR_STR(ROOT_ADS_R_side,CSTRING(ROOT_ADS_R_side),CSTRING(ROOT_ADS_R_side_desc),"""east""");
            ATTR_BOOL(ROOT_ADS_R_collect,CSTRING(ROOT_ADS_R_collect),CSTRING(ROOT_ADS_R_collect_desc),true);
            ATTR_STR(ROOT_ADS_R_uniform,CSTRING(ROOT_ADS_R_uniform),CSTRING(ROOT_ADS_R_uniform_desc),"""""");
            ATTR_STR(ROOT_ADS_R_vest,CSTRING(ROOT_ADS_R_vest),CSTRING(ROOT_ADS_R_vest_desc),"""""");
            ATTR_STR(ROOT_ADS_R_headgear,CSTRING(ROOT_ADS_R_headgear),CSTRING(ROOT_ADS_R_headgear_desc),"""""");
            ATTR_STR(ROOT_ADS_R_primary,CSTRING(ROOT_ADS_R_primary),CSTRING(ROOT_ADS_R_primary_desc),"""""");
            ATTR_STR(ROOT_ADS_R_launcher,CSTRING(ROOT_ADS_R_launcher),CSTRING(ROOT_ADS_R_launcher_desc),"""""");
            ATTR_STR(ROOT_ADS_R_backpack,CSTRING(ROOT_ADS_R_backpack),CSTRING(ROOT_ADS_R_backpack_desc),"""""");
            ATTR_STR(ROOT_ADS_R_facewear,CSTRING(ROOT_ADS_R_facewear),CSTRING(ROOT_ADS_R_facewear_desc),"""""");
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_GearReference_desc);
        };
    };

    class ROOT_ADS_Module_Compromise: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_Compromise),edenCompromise,1);
        class Attributes: AttributesBase {
            class ROOT_ADS_C_action: Combo {
                property = "ROOT_ADS_C_action";
                displayName = CSTRING(ROOT_ADS_C_action);
                tooltip = CSTRING(ROOT_ADS_C_action_desc);
                typeName = "NUMBER";
                defaultValue = 0;
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_C_action_v0); value = 0; };
                    class V1 { name = CSTRING(ROOT_ADS_C_action_v1); value = 1; };
                    class V2 { name = CSTRING(ROOT_ADS_C_action_v2); value = 2; };
                };
            };
            ATTR_STR(ROOT_ADS_C_sides,CSTRING(ROOT_ADS_C_sides),CSTRING(ROOT_ADS_C_sides_desc),"""""");
            ATTR_NUM(ROOT_ADS_C_radius,CSTRING(ROOT_ADS_C_radius),CSTRING(ROOT_ADS_C_radius_desc),-1);
            ATTR_BOOL(ROOT_ADS_C_allPlayers,CSTRING(ROOT_ADS_C_allPlayers),CSTRING(ROOT_ADS_C_allPlayers_desc),true);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_Compromise_desc);
        };
    };

    class ROOT_ADS_Module_Toggle: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_Toggle),edenToggle,1);
        class Attributes: AttributesBase {
            class ROOT_ADS_T_action: Combo {
                property = "ROOT_ADS_T_action";
                displayName = CSTRING(ROOT_ADS_T_action);
                tooltip = CSTRING(ROOT_ADS_T_action_desc);
                typeName = "NUMBER";
                defaultValue = 0;
                class Values {
                    class V0 { name = CSTRING(ROOT_ADS_T_action_v0); value = 0; };
                    class V1 { name = CSTRING(ROOT_ADS_T_action_v1); value = 1; };
                    class V2 { name = CSTRING(ROOT_ADS_T_action_v2); value = 2; };
                };
            };
            ATTR_NUM(ROOT_ADS_T_delay,CSTRING(ROOT_ADS_T_delay),CSTRING(ROOT_ADS_T_delay_desc),0);
            ATTR_NUM(ROOT_ADS_T_duration,CSTRING(ROOT_ADS_T_duration),CSTRING(ROOT_ADS_T_duration_desc),0);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_Toggle_desc);
        };
    };

    class ROOT_ADS_Module_Bulletin: Module_F {
        EDEN_MODULE_BASE(CSTRING(eden_ROOT_ADS_Module_Bulletin),edenBulletin,1);
        class Attributes: AttributesBase {
            ATTR_STR(ROOT_ADS_B_sides,CSTRING(ROOT_ADS_B_sides),CSTRING(ROOT_ADS_B_sides_desc),"""east""");
            ATTR_BOOL(ROOT_ADS_B_burn,CSTRING(ROOT_ADS_B_burn),CSTRING(ROOT_ADS_B_burn_desc),true);
            ATTR_BOOL(ROOT_ADS_B_wanted,CSTRING(ROOT_ADS_B_wanted),CSTRING(ROOT_ADS_B_wanted_desc),true);
            ATTR_BOOL(ROOT_ADS_B_clear,CSTRING(ROOT_ADS_B_clear),CSTRING(ROOT_ADS_B_clear_desc),false);
            ATTR_NUM(ROOT_ADS_B_duration,CSTRING(ROOT_ADS_B_duration),CSTRING(ROOT_ADS_B_duration_desc),-1);
            ATTR_NUM(ROOT_ADS_B_range,CSTRING(ROOT_ADS_B_range),CSTRING(ROOT_ADS_B_range_desc),0);
            class ModuleDescription: ModuleDescription {};
        };
        class ModuleDescription: ModuleDescription {
            description = CSTRING(eden_ROOT_ADS_Module_Bulletin_desc);
        };
    };
};
